version: "3"

secrets:
  db_passwd:
    file: db_passwd.txt

services:
  bot:
    image: "ssttkkl/bot-kuraku:latest"
    container_name: "bot"
    environment:
      - "HOST=0.0.0.0"
      - "PORT=8080"
    volumes:
      - ./.env:/app/.env.prod

  bot-gocq:
    image: "silicer/go-cqhttp:latest"
    container_name: "bot-gocq"
    volumes:
      - "bot-gocq-data:/data"

  bot-qsign:
    image: "xzhouqd/qsign:8.9.63"
    container_name: "bot_qsign"
    env_file:
      - qsign.env

  bot-postgres:
    image: "postgres:latest"
    container_name: "bot-postgres"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_passwd
    volumes:
      - "bot-postgres-data:/var/lib/postgresql/data"
    secrets:
      - db_passwd

volumes:
  bot-gocq-data:
  bot-postgres-data:
